name: Build and Create Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  update-meta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update version or generate files
        run: |
          python3 .github/update-meta.py

      - name: Commit changes
        run: |
          git add .
          git commit -m "chore: update meta.json"
          git push origin HEAD:master
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Read Pack Config
      id: config
      run: |
        MINECRAFT_VERSION=$(jq -r '.mc_version' pack.json)
        PACK_VERSION=$(jq -r '.pack_version' pack.json)
        echo "MINECRAFT_VERSION=${MINECRAFT_VERSION}" >> $GITHUB_OUTPUT
        echo "PACK_VERSION=${PACK_VERSION}" >> $GITHUB_OUTPUT
    - name: Create ZIP file
      run: |
        python3 build.py
        ZIP_NAME="Meowdpack ${{ steps.config.outputs.PACK_VERSION }}.mrpack"
        echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV
        mv pack-dev-build.mrpack "$ZIP_NAME"

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: resource-pack-artifact
        path: ${{ env.ZIP_NAME }}
        
    - name: Read changelog file
      id: changelog
      run: |
        # Decode GitHub-encoded newlines
        CHANGELOG=$(cat changelog.md)
        CHANGELOG="${CHANGELOG//'%0A'/$'\n'}"
        CHANGELOG="${CHANGELOG//'%0D'/$'\r'}"
        CHANGELOG="${CHANGELOG//'%25'/'%'}"
        echo "DECODED_CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ${{ steps.changelog.outputs.DECODED_CHANGELOG }}
          #### Automated release created by GitHub Actions
        draft: false
        prerelease: false
    - name: Upload Release Artifact
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "${{ env.ZIP_NAME }}"
        asset_name: "${{ env.ZIP_NAME }}"
        asset_content_type: application/zip
    - name: "Actions for Discord"
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: "Meodpack"
        DISCORD_AVATAR: https://picsum.photos/500/500
        DISCORD_MENTIONS: >-
          {
            "content": "<@&1325601502550818846>",
            "allowed_mentions": {
              "roles": ["1325601502550818846"]
            }
          }

      uses: Ilshidur/action-discord@0.4.0
      with:
        args: "${{ steps.changelog.outputs.DECODED_CHANGELOG }}\nDownload: https://github.com/ThatCuteOne/meowdpack/releases/tag/v${{ steps.config.outputs.PACK_VERSION }}"
